FROM node:14-alpine

WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the application will listen
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
