# Utilisez une image de base avec Node.js
FROM node:14

# Créez un répertoire pour l'application
WORKDIR /app

# Copiez package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste du code de l'application
COPY . .

# Exposez le port sur lequel votre application sera accessible
EXPOSE 3003

# Démarrez l'application
CMD ["npm", "start"]